### ISSUE TITLE
Micro-AUC vs. Macro-AUC | Ablations

### ISSUE THREAD

**Issue by jakubmicorek** [lilygeorgescu/AED-SSMTL#1]
Hi, thank you for your interesting work!
I assume that you reported only the Macro-AUC throughout the paper. Is there any chance to get the Micro-AUC for the ablation scores? - Especially on the UCSD Ped2 dataset. This would help me out by a lot. Thank you!

**Comment by lilygeorgescu** [comment]
Hi,  

Yes, we reported only the Macro-AUC score. Are you interested in some specific part of the ablation table?

**Comment by jakubmicorek** [comment]
Hi, 

I would specifically be interested in the AUC results of Table 4 for UCSD Ped2, where the number of tasks is 1 for each of the four tasks, and where the number of tasks is 4 on object level and on frame level. 

Thank you a lot! 
KR

**Comment by lilygeorgescu** [comment]
Here are the micro-AUC scores:
Task 1 (forward/backward) - 0.818
Task 2 (irregular motion) - 0.82
Task 3 (middle bbox) -  0.936
Task 4 (kd) -  0.964

4 Tasks (shallow + narrow) -  0.921
4 Tasks (deep + narrow) -  0.942
4 Tasks (shallow + wide) -   0.929

Lili

**Comment by BenedictGreen** [comment]
Hi,
Thanks for you interesting work!
I thought that the micro-AUC scores result above is on frame level, Am I right? Other results can be found in Table 4.

**Comment by lilygeorgescu** [comment]
Hi,

The results mentioned above are micro-AUC scores, the macro-AUC scores for all the ablation study can be found in Table 4.

Best,
Lili
