### ISSUE TITLE
Request Code CVPR-2021

### ISSUE THREAD

**Issue by zdl12345678** [lilygeorgescu/AED-SSMTL#10]
Hi @lilygeorgescu ,

I've sent an email to you with the signed forms two weeks ago but haven't yet received any response. Just want to double check if you have replied to the requests for the last two week yet?

**Comment by wxqpxw** [comment]
me, too : )

**Comment by lilygeorgescu** [comment]
Hi,

I apologize for my late reply.
I have answered all the email received up to date.

If you did not receive a reply from me, please let me know your email address to search it in the spam folder. 

Best,
Lili

**Comment by wxqpxw** [comment]
Hi @lilygeorgescu ,
I have sent you a new email again from wwxxqq@buaa.edu.cn.
May I trouble you to check again?

**Comment by zdl12345678** [comment]
> Hi,
> 
> I apologize for my late reply. I have answered all the email received up to date.
> 
> If you did not receive a reply from me, please let me know your email address to search it in the spam folder.
> 
> Best, Lili

Hi @lilygeorgescu ,
I have sent you a email again from 2021102110061@whu.edu.cn.
May I trouble you to check again? 
Thank U

**Comment by lilygeorgescu** [comment]
Hi,

I have just replied to you.

Best,
Lili
