### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by ganqieniurou** [lilygeorgescu/AED-SSMTL#13]
hi @raduionescu 
thanks for the great work
I've send the email for code request about 5 weeks ago but I haven't receive the source code yet. I sent another email for code request yesterday. The emails are sent from 2100727@stu.neu.edu.cn. It is for pure academic purpose.
much appreciated

**Comment by ganqieniurou** [comment]
hi @lilygeorgescu 
thanks again for your great work
I've reformed the agreement as requested in your reply and send the email 2 weeks ago but have not received any response yet.

**Comment by lilygeorgescu** [comment]
Hi Zhewen,

We sent you a reply more then two weeks ago with further instructions. Please follow the instruction (send us the pdf file) and I will send you the code at once.

Best,
Lili

**Comment by ganqieniurou** [comment]
hi @lilygeorgescu 
I've reformed the agreement as requested in your reply and send the email on Jan 27th and Feb 14th. Just want to double check if you have received such email. Thanks
