### ISSUE TITLE
How to do evaluation on a video

### ISSUE THREAD

**Issue by imdsafi09** [lilygeorgescu/AED-SSMTL#15]
First of all, thank you for open-sourcing your code to us. I have the following question and would be thankful if you could answer it.
1- I train the model and generate the weight following the instructions in the Readme file using the Ped2 dataset. However, running the test script gives me output in the "npy" file. Can we test the model that provides us with results directly on the videos similar to the one you uploaded?
2- Can I convert npy files to images to visualize anomaly detections? If yes, is there any script you already have, or do I need to convert it manually?

**Comment by lilygeorgescu** [comment]
Hi,

Sorry for my late reply.
1. Yes, you can test on different videos, one of the npy file contains the anomaly map on each frame.
2. Yes, you can convert the npy volume to visualize the anomaly. you only have to overlay the anomaly score map on the current frame.

Best,
Lili
