### ISSUE TITLE
about testing！！！

### ISSUE THREAD

**Issue by Smallwhite999** [lilygeorgescu/AED-SSMTL#16]
I have a few questions I'd like to ask:

1. If the program runs multiple times with the same set of parameters, will the training model saved in the current run overwrite the model from the previous run?
2. For multiple models trained with different parameters, how can I modify the parameters to test a specific model in `test.py`? I couldn't find the parameters that need modification inside it.

Thank you,

Sincerely

**Comment by lilygeorgescu** [comment]
Hi,

I answered your question through email.
