### ISSUE TITLE
Code request after signing and sending emails to specified application address

### ISSUE THREAD

**Issue by JPerAsperaadAstra** [lilygeorgescu/AED-SSMTL#17]
Hello, dear authors. Thanks for your great work and I'm willing to try this method out. I send emails to this repository's specified application address but got no reply.
Could you please check and reply to my request email? Thanks a lot :)

**Comment by lilygeorgescu** [comment]
Thank you for your interest in our work! Email sent!

**Comment by yinyexingchen** [comment]
> Hello, dear authors. Thanks for your great work and I'm willing to try this method out. I send emails to this repository's specified application address but got no reply. Could you please check and reply to my request email? Thanks a lot :)

hello,have you receive the code?Could you please share me?thanks a lot.My address is 20201071488@mail.dlut.edu.cn
