### ISSUE TITLE
I have similar problem. I submitted the signed agreement but no answer!

### ISSUE THREAD

**Issue by amnikoo** [lilygeorgescu/AED-SSMTL#3]
Hello.sir! 

I’m writing with regard to the application for your source code that I have submitted on November 18, 2021. It’s been a week since my application, and I still haven’t received any updates, so I’m just wondering if you would be kind enough to provide some help. 

Btw, the code  will be only used for my academic research, and I’ve signed the agreement and attached it to the email. 

Many thanks to your help!

_Originally posted by @EdwardLocke in https://github.com/lilygeorgescu/AED-SSMTL/issues/2#issuecomment-981225064_

**Comment by amnikoo** [comment]
Hi,
Please answer my request. Thank you for your help.

**Comment by amnikoo** [comment]
Hi,
Please answer my request. Thank you for your help.

**Comment by lilygeorgescu** [comment]
Hi,

I answered all the source code requests. If I did not answer you, please resent the email or tell me your email address to look for it in my inbox/spam folder.

Best,
Lili

**Comment by amnikoo** [comment]
Hi, thank you for your answer.

My email is a_nikokaran@comp.iust.ac.ir

Thanks for your help :)

**Comment by lilygeorgescu** [comment]
Hi,

I have found your mail in the spam folder and I sent the code to you. In order to avoid getting your email to the spam folder, it is recommended to write a subject or a content in the mail. 

Best,
Lili

**Comment by amnikoo** [comment]
> Hi,
> 
> I have found your mail in the spam folder and I sent the code to you. In order to avoid getting your email to the spam folder, it is recommended to write a subject or a content in the mail.
> 
> Best, Lili

Hi,

Oh sry my bad.

Thank you very much.

**Comment by Meenn** [comment]
Hi,sir!
I have the same problem just like amnikoo.I have submitted the application for the code on February 21, 2022.Since then,I haven’t received any updates.I’m wondering if you have received my email (attached with the agreement I've signed).

The code will be only used for my academic research.

Looking forward to your reply.

Thank you very much.
