### ISSUE TITLE
I submitted the signed agreement but didn't get the code!

### ISSUE THREAD

**Issue by Meenn** [lilygeorgescu/AED-SSMTL#4]
Hi,sir!
I have the same problem just like amnikoo.I have submitted the application for the code on February 21, 2022.Since then,I haven’t received any updates.I’m wondering if you have received my email (attached with the agreement I've signed).

The code will be only used for my academic research.

Looking forward to your reply.

Thank you very much.

**Comment by lilygeorgescu** [comment]
Hi ,

I answered to all the code requests that I received so far including from Feb 21st.  If you did not receive an email from me, please let me know.

Best,
Lili Georgescu

**Comment by Meenn** [comment]
Hello,sir.Thanks for you reply!

I haven't received any reply since  submitting the application.My email is [mengxiaoxi@csu.edu.cn](mailto:mengxiaoxi@csu.edu.cn).
Thanks for your help and looking forward to your reply.

All best wishes

**Comment by lilygeorgescu** [comment]
I sent you an email 20 mins ago. Can you check your spam folder?

**Comment by Meenn** [comment]
Yes,sir.

I have received the email just now.Many thanks for your help.

Best!
