### ISSUE TITLE
Questions about frame-level detection

### ISSUE THREAD

**Issue by hongsi96** [lilygeorgescu/AED-SSMTL#7]
Hi,

I have a question about the frame-level detection experiment.

In the case of object-level detection, the cropped image extracted with the YOLOv3 detector is resized to a 64 × 64 pixel image. And this is clear. 
But, In the case of frame-level detection, I wonder how to pre-process the original video (image).
Are you resizing in the same way (64 × 64 pixel image)? Or is it some other preprocessing process?

It would be helpful to give the necessary information to reproduce the frame-level detection experiment.

Thank you,
Sincerely yours,

Seokil

**Comment by lilygeorgescu** [comment]
Hi Seokil,

Apologize for my late reply. In the case of frame-level detection, we resized the images to 256x256. My co-author @antoniobarbalau can give you more details about this experiment.

Best,
Lili

**Comment by hongsi96** [comment]
Thank you for reply.
Actually, I tried to resize it to 256x256, but the performance listed in the paper did not come out.

If there is additional information needed for frame-level detection experiment reproduction, can you share it?

@antoniobarbalau I would be very grateful if you could share any elements that could be a clue.
