### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by knbandit** [lilygeorgescu/AED-SSMTL#9]
Hi @lilygeorgescu ,

I've sent an email to you with the signed forms two weeks ago but haven't yet received any response. Just want to double check if you have replied to the requests for the last two week yet?

**Comment by lilygeorgescu** [comment]
Hi @knbandit,

I replied to all the request received in the last 2+ weeks. I apologize for my late reply, it was and still is a very busy period for me.

Please check your inbox, if you did not receive an email from me, let me know.

Best regards,
Lili
